<?xml version="1.0" encoding="UTF-8"?>
<testsuites>
    <testsuite name="shop-for-localhost;view-product-detail" tests="2" failures="1" skipped="0">
        <properties>
            <property name="@localhost" value="true">
            </property>
            <property name="URI" value="C:\workspace\development\201708\node_modules\selenium-cucumber-js\features\test.localhost.feature">
            </property>
        </properties>
        <testcase name="Given I navigate to &quot;http://localhost:63342/DB123/development/content/financial_tools/tool02.html?_ijt=5nof9tq0vaqsi4uoqlaem1pest&quot;" classname="shop-for-localhost;view-product-detail" time="6.988136141">
        </testcase>
        <testcase name="Then element &quot;#income&quot; &quot;value&quot; should be &quot;1000&quot;" classname="shop-for-localhost;view-product-detail" time="57.020605192">
            <failure message="TypeError: re.exec is not a function">TypeError: re.exec is not a function
    at Assertion.assertMatch (C:\workspace\development\201708\node_modules\chai\lib\chai\core\assertions.js:1075:12)
    at Assertion.ctx.(anonymous function) [as match] (C:\workspace\development\201708\node_modules\chai\lib\chai\utils\addMethod.js:41:25)
    at createWorld.&lt;anonymous&gt; (C:\workspace\development\201708\node_modules\selenium-cucumber-js\step-definitions\test-localhost-steps.js:51:39)
    at _combinedTickCallback (internal/process/next_tick.js:73:7)
    at process._tickCallback (internal/process/next_tick.js:104:9)</failure>
        </testcase>
    </testsuite>
</testsuites>